Solution
mate-academy/py-game-models pull request #688
Opened 2024-02-21 20:02 UTC by oleksandr-lysanets

2024-02-21 20:02 UTC, closed without merging

2024-02-22 10:06 UTC, vasylhnatiuk requested changes

2024-02-22 10:06 UTC, vasylhnatiuk commented on db/models.py
> +    name = models.CharField(max_length=255, choices=races, unique=True)
how can you use choices if name must be unique? delete choices

2024-02-22 10:52 UTC, vasylhnatiuk approved these changes

2024-02-26 15:39 UTC, NikOneZ1 approved these changes